"""Added position column

Revision ID: 58f4f7f194b1
Revises: 9c8139cfe837
Create Date: 2021-09-19 23:18:49.065231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58f4f7f194b1'
down_revision = '9c8139cfe837'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crop', sa.Column('position', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crop', 'position')
    # ### end Alembic commands ###
