"""Deleted crop_positions

Revision ID: 6a99095e21a6
Revises: 58f4f7f194b1
Create Date: 2021-09-19 23:28:27.041578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a99095e21a6'
down_revision = '58f4f7f194b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('crop', 'picture',
    #            existing_type=sa.BLOB(),
    #            nullable=False)
    # op.alter_column('crop', 'position',
    #            existing_type=sa.TEXT(),
    #            nullable=False)
    # op.alter_column('crop', 'width',
    #            existing_type=sa.INTEGER(),
    #            nullable=False)
    # op.alter_column('crop', 'height',
    #            existing_type=sa.INTEGER(),
    #            nullable=False)
    # op.alter_column('crop', 'index',
    #            existing_type=sa.INTEGER(),
    #            nullable=False)
    op.drop_column('meme', 'crop_positions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meme', sa.Column('crop_positions', sa.TEXT(), nullable=True))
    # op.alter_column('crop', 'index',
    #            existing_type=sa.INTEGER(),
    #            nullable=True)
    # op.alter_column('crop', 'height',
    #            existing_type=sa.INTEGER(),
    #            nullable=True)
    # op.alter_column('crop', 'width',
    #            existing_type=sa.INTEGER(),
    #            nullable=True)
    # op.alter_column('crop', 'position',
    #            existing_type=sa.TEXT(),
    #            nullable=True)
    # op.alter_column('crop', 'picture',
    #            existing_type=sa.BLOB(),
    #            nullable=True)
    # ### end Alembic commands ###
