"""Created tables

Revision ID: 9c8139cfe837
Revises: 
Create Date: 2021-09-19 15:26:19.998283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c8139cfe837'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crop', sa.Column('width', sa.Integer(), nullable=True))
    op.add_column('crop', sa.Column('height', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crop', 'height')
    op.drop_column('crop', 'width')
    # ### end Alembic commands ###
