"""Renamed post_id in post

Revision ID: 9f385bdf6e3f
Revises: 
Create Date: 2021-09-11 22:25:21.409830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f385bdf6e3f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crop')
    op.drop_table('public')
    op.drop_table('post')
    op.drop_table('meme')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meme',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('public_id', sa.VARCHAR(length=15), nullable=False),
    sa.Column('post_id', sa.VARCHAR(length=10), nullable=False),
    sa.Column('picture', sa.BLOB(), nullable=False),
    sa.Column('index', sa.INTEGER(), nullable=True),
    sa.Column('crop_positions', sa.BLOB(), nullable=True),
    sa.ForeignKeyConstraint(['public_id', 'post_id'], ['post.public_id', 'post.post_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post',
    sa.Column('public_id', sa.VARCHAR(length=15), nullable=False),
    sa.Column('post_id', sa.VARCHAR(length=10), nullable=False),
    sa.Column('date', sa.VARCHAR(length=30), nullable=False),
    sa.Column('text', sa.TEXT(), nullable=True),
    sa.Column('comments', sa.INTEGER(), nullable=True),
    sa.Column('likes', sa.INTEGER(), nullable=True),
    sa.Column('reposts', sa.INTEGER(), nullable=True),
    sa.Column('views', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['public_id'], ['public.id'], ),
    sa.PrimaryKeyConstraint('public_id', 'post_id')
    )
    op.create_table('public',
    sa.Column('id', sa.VARCHAR(length=15), nullable=False),
    sa.Column('domain', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', 'domain')
    )
    op.create_table('crop',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('meme_id', sa.INTEGER(), nullable=True),
    sa.Column('picture', sa.BLOB(), nullable=True),
    sa.Column('index', sa.INTEGER(), nullable=True),
    sa.Column('text', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['meme_id'], ['meme.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
