"""Added text, renamed columns

Revision ID: b221d40e9fe3
Revises: 
Create Date: 2021-09-10 11:01:19.186840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b221d40e9fe3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crop', sa.Column('index', sa.Integer(), nullable=True))
    op.add_column('crop', sa.Column('text', sa.Text(), nullable=True))
    op.drop_column('crop', 'crop_index')
    op.add_column('meme', sa.Column('index', sa.Integer(), nullable=True))
    op.drop_column('meme', 'picture_index')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meme', sa.Column('picture_index', sa.INTEGER(), nullable=True))
    op.drop_column('meme', 'index')
    op.add_column('crop', sa.Column('crop_index', sa.INTEGER(), nullable=True))
    op.drop_column('crop', 'text')
    op.drop_column('crop', 'index')
    # ### end Alembic commands ###
